# Generated by Django 2.2.7 on 2019-12-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(default='2015-11-9', verbose_name='Дата рождения'),
            preserve_default=False,
        ),
    ]
