# Generated by Django 2.2.7 on 2019-12-01 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_profile_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='profile_photo/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
