# Generated by Django 2.2.7 on 2019-12-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20191201_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium',
            field=models.BooleanField(default=False, verbose_name='Премиум аккаунт'),
        ),
    ]
