# Generated by Django 2.2.7 on 2019-12-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20191203_2220'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='Описание фотографии'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='portfolio_images/%Y/%m/%d', verbose_name='Фотография'),
        ),
    ]
