# Generated by Django 2.2.7 on 2019-12-07 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20191207_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='from_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Profile', verbose_name='Клиент'),
        ),
    ]
