# Generated by Django 2.2.7 on 2019-12-08 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20191207_1933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='from_profile',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='regions',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='kind',
            new_name='role',
        ),
    ]
